esphome:
  name: qtpy-esp32s2

external_components:
  - source: github://pr#3307
    components: [ ms8607 ]

esp32:
  board: lolin_s2_mini
  variant: ESP32S2
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 5.0.0


api:
ota:
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  - id: stemma
    sda: 41
    scl: 40
    scan: true

switch:
  - platform: gpio
    pin: 38
    name: "neopixel-enable"
    restore_mode: ALWAYS_ON
    internal: true

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: 39
    num_leds: 1
    name: "NeoPixel"
sensor:
  - platform: ms8607
    temperature:
      name: Temperature
    humidity:
      name: Humidity
    pressure:
      name: Pressure